<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
<?php 
    $articles = Mage::getModel('article/article')->getCollection();
    $time = time();
    foreach($articles as $article){
        $article->setTotalBets($article->getAgree() + $article->getDisagree())->save();
        $deadline = strtotime($article->getDeadlineTime());
        $diff = $time - $deadline;
        if($diff > 0){
            $article->setStatus('waiting')->save();
        }            
    }   
?>
<?php echo $this->getChildHtml('head') ?>
<meta name="google-site-verification" content="5s4cOPihj4w5iO2kaaYl5_BZSV1S3Nf82zFp8b4ZuUM" />
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<?php echo $this->getChildHtml('header') ?>
    <div id="main">
   <div class="wrapper">
      <div id="content">
         <div id="page-content">
            <br/>
            <div class="two-third">
               <h6>Bets of Bitcoin is a website where you can bet bitcoins on real world events. There are two ways to earn bitcoins:</h6>
            </div>
            <div class="clear"></div>
            <div class="one-third">
               <a href="<?php echo $this->getUrl('article/index') ?>">
                  <p class="green-box">Bet on existing statements.<br />Early bets win more.</p>
               </a>
            </div>
            <div class="one-third">
               <a href="<?php echo $this->getUrl('article/index/new') ?>">
                  <p class="green-box">Submit new statements.<br />Submitters earn commission.</p>
               </a>
            </div>
            <div class="clear"></div>
            <div class="two-third">
               <h6 class="line-divider">
                  You can <a href="<?php echo $this->getUrl('help') ?>">read more</a> about how to use the site.<br />
                  <p class="information-box">Did you know that we have a <a href="#">Twitter account</a> where we post the new statements?</p>
                  Here are some of the statements available for betting:
               </h6>
               <ul class="tabs">
                  <li><a href="#"><span>Earliest deadline</span></a></li>
                  <li><a href="#"><span>Highest bets</span></a></li>
                  <li><a href="#"><span>Newest</span></a></li>
               </ul>
               <div class="panes">
                  <div>
                     <?php 
                        $posts = Mage::getModel('article/article')->getCollection()
                                    ->setPageSize(10)
                                    ->setCurPage(1)
                                    ->addFieldToFilter('status', 'available')
                                    ->setOrder('deadline_time', 'ASC')
                                    ->load();
                        $highest = Mage::getModel('article/article')->getCollection()
                                    ->setPageSize(10)
                                    ->setCurPage(1)
                                    ->addFieldToFilter('status', 'available')
                                    ->setOrder('total_bets', 'DESC')
                                    ->load();
                        $newest = Mage::getModel('article/article')->getCollection()
                                    ->setPageSize(10)
                                    ->setCurPage(1)
                                    ->addFieldToFilter('status', 'available')
                                    ->setOrder('created_time', 'ASC')
                                    ->load();                   
                      ?>
                     <?php foreach($posts as $post): ?>
                        <div class="filter">
                        <a href="<?php echo $this->getUrl('article/index/item?id=' . $post->getArticleId()) ?>">
                           <h6><?php echo $post->getTitle() ?></h6>
                        </a>
                        <li class="agree"><?php echo $post->getAgree() ?></li>
                        <li class="disagree"><?php echo $post->getDisagree() ?></li>
                        <li class="active"><?php echo Mage::helper('article')->timeCountdown($post->getDeadlineTime(), $post->getStatus())   ?></li>
                     </div>
                     <div class="line-divider"></div>
                     <?php endforeach; ?>
                  </div>
                  <div>
                     <?php foreach($highest as $post): ?>
                        <div class="filter">
                        <a href="<?php echo $this->getUrl('article/index/item?id=' . $post->getArticleId()) ?>">
                           <h6><?php echo $post->getTitle() ?></h6>
                        </a>
                        <li class="agree"><?php echo $post->getAgree() ?></li>
                        <li class="disagree"><?php echo $post->getDisagree() ?></li>
                        <li class="active"><?php echo Mage::helper('article')->timeCountdown($post->getDeadlineTime(), $post->getStatus())   ?></li>
                     </div>
                     <div class="line-divider"></div>
                     <?php endforeach; ?>
                  </div>
                  <div>
                     <?php foreach($newest as $post): ?>
                        <div class="filter">
                        <a href="<?php echo $this->getUrl('article/index/item?id=' . $post->getArticleId()) ?>">
                           <h6><?php echo $post->getTitle() ?></h6>
                        </a>
                        <li class="agree"><?php echo $post->getAgree() ?></li>
                        <li class="disagree"><?php echo $post->getDisagree() ?></li>
                        <li class="active"><?php echo Mage::helper('article')->timeCountdown($post->getDeadlineTime(), $post->getStatus())   ?></li>
                     </div>
                     <div class="line-divider"></div>
                     <?php endforeach; ?>
                  </div>
               </div>
               We have <a href="<?php echo $this->getUrl('article/index') ?>">more statements</a> to bet.
            </div>
         </div>
      </div>
   </div>
</div>
<?php echo $this->getChildHtml('footer') ?>
</body>
</html>