<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
<?php echo $this->getChildHtml('head') ?>
<meta name="google-site-verification" content="5s4cOPihj4w5iO2kaaYl5_BZSV1S3Nf82zFp8b4ZuUM" />
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<?php echo $this->getChildHtml('header') ?>
    <div id="main">
   <div class="wrapper">
      <div id="content">
         <div id="page-content">
            <br/>
            <div class="two-third">
               <h6>Bets of Bitcoin is a website where you can bet bitcoins on real world events. There are two ways to earn bitcoins:</h6>
            </div>
            <div class="clear"></div>
            <div class="one-third">
               <a href="/list">
                  <p class="green-box">Bet on existing statements.<br>Early bets win more.</p>
               </a>
            </div>
            <div class="one-third">
               <a href="/submit">
                  <p class="green-box">Submit new statements.<br>Submitters earn commission.</p>
               </a>
            </div>
            <div class="clear"></div>
            <div class="two-third">
               <h6 class="line-divider">
                  You can <a href="/help">read more</a> about how to use the site.<br>
                  <p class="information-box">Did you know that we have a <a href="https://twitter.com/#!/betsofbitcoin">Twitter account</a> where we post the new statements?</p>
                  Here are some of the statements available for betting:
               </h6>
               <ul class="tabs">
                  <li><a href="#"><span>Earliest deadline</span></a></li>
                  <li><a href="#"><span>Highest bets</span></a></li>
                  <li><a href="#"><span>Newest</span></a></li>
               </ul>
               <div class="panes">
                  <div>
                     <div class="filter">
                        <a href="/item?id=1414">
                           <h6>Bitcoin price will be $95 or more at 15th of April 2013</h6>
                        </a>
                        <li class="agree">23.63</li>
                        <li class="disagree">6.80</li>
                        <li class="active">2 days</li>
                     </div>
                     <div class="line-divider"></div>
                     <div class="filter">
                        <a href="/item?id=1361">
                           <h6>The Government of Cyprus Will Enact a Bank Deposit Tax By April 15, 2013</h6>
                        </a>
                        <li class="agree">0.20</li>
                        <li class="disagree">0.90</li>
                        <li class="active">2 days</li>
                     </div>
                     <div class="line-divider"></div>
                     <div class="filter">
                        <a href="/item?id=1129">
                           <h6>Two million people will be without electricity due to a natural event before April, 15 2013</h6>
                        </a>
                        <li class="agree">3.30</li>
                        <li class="disagree">112.95</li>
                        <li class="active">3 days</li>
                     </div>
                     <div class="line-divider"></div>
                     <div class="filter">
                        <a href="/item?id=1499">
                           <h6>Bitcoin will reach $350 by May 1st 2013</h6>
                        </a>
                        <li class="agree">10.53</li>
                        <li class="disagree">19.07</li>
                        <li class="active">3 days</li>
                     </div>
                     <div class="line-divider"></div>
                     <div class="filter">
                        <a href="/item?id=1273">
                           <h6>Bitcoin will be traded $55 at some point in May on MtGox</h6>
                        </a>
                        <li class="agree">12.43</li>
                        <li class="disagree">1.90</li>
                        <li class="active">4 days</li>
                     </div>
                     <div class="line-divider"></div>
                     <div class="filter">
                        <a href="/item?id=1476">
                           <h6>There will be 10 or more CVEs for WebKit published in the month of April.</h6>
                        </a>
                        <li class="agree">0.20</li>
                        <li class="disagree">1.05</li>
                        <li class="active">4 days</li>
                     </div>
                     <div class="line-divider"></div>
                     <div class="filter">
                        <a href="/item?id=1263">
                           <h6>LA Lakers will not make it to the playoffs on April 20, 2013</h6>
                        </a>
                        <li class="agree">0.22</li>
                        <li class="disagree">0.25</li>
                        <li class="active">1 week</li>
                     </div>
                     <div class="line-divider"></div>
                     <div class="filter">
                        <a href="/item?id=1478">
                           <h6>U.S. will declare war on N. Korea by May 2013.</h6>
                        </a>
                        <li class="agree">0.10</li>
                        <li class="disagree">0.90</li>
                        <li class="active">1 week, 2 days</li>
                     </div>
                     <div class="line-divider"></div>
                     <div class="filter">
                        <a href="/item?id=1248">
                           <h6>The Miami Heat will win the 2013 NBA finals</h6>
                        </a>
                        <li class="agree">0.10</li>
                        <li class="disagree">0.10</li>
                        <li class="active">1 week, 2 days</li>
                     </div>
                     <div class="line-divider"></div>
                     <div class="filter">
                        <a href="/item?id=1086">
                           <h6>mtgoxUSD price will hit $7.58 Aug 2012 low before May 2013</h6>
                        </a>
                        <li class="agree">3.60</li>
                        <li class="disagree">109.58</li>
                        <li class="active">1 week, 3 days</li>
                     </div>
                     <div class="line-divider"></div>
                  </div>
                  <div>
                     <div class="filter">
                        <a href="/item?id=665">
                           <h6>Butterfly Labs ASIC is real and will achieve 350+ Mhash/Joule</h6>
                        </a>
                        <li class="agree">137.82</li>
                        <li class="disagree">98.91</li>
                        <li class="active">2 months, 2 weeks</li>
                     </div>
                     <div class="line-divider"></div>
                     <div class="filter">
                        <a href="/item?id=1129">
                           <h6>Two million people will be without electricity due to a natural event before April, 15 2013</h6>
                        </a>
                        <li class="agree">3.30</li>
                        <li class="disagree">112.95</li>
                        <li class="active">3 days</li>
                     </div>
                     <div class="line-divider"></div>
                     <div class="filter">
                        <a href="/item?id=1086">
                           <h6>mtgoxUSD price will hit $7.58 Aug 2012 low before May 2013</h6>
                        </a>
                        <li class="agree">3.60</li>
                        <li class="disagree">109.58</li>
                        <li class="active">1 week, 3 days</li>
                     </div>
                     <div class="line-divider"></div>
                     <div class="filter">
                        <a href="/item?id=970">
                           <h6>Assault weapons sales ban will be reinstated before Jan 1 2014.</h6>
                        </a>
                        <li class="agree">5.10</li>
                        <li class="disagree">34.90</li>
                        <li class="active">8 months, 3 weeks</li>
                     </div>
                     <div class="line-divider"></div>
                     <div class="filter">
                        <a href="/item?id=440">
                           <h6>Germany will stop using the Euro or re-introduce the D-Mark as national currency by July 1st 2013</h6>
                        </a>
                        <li class="agree">1.30</li>
                        <li class="disagree">29.91</li>
                        <li class="active">2 months, 2 weeks</li>
                     </div>
                     <div class="line-divider"></div>
                     <div class="filter">
                        <a href="/item?id=1414">
                           <h6>Bitcoin price will be $95 or more at 15th of April 2013</h6>
                        </a>
                        <li class="agree">23.63</li>
                        <li class="disagree">6.80</li>
                        <li class="active">2 days</li>
                     </div>
                     <div class="line-divider"></div>
                     <div class="filter">
                        <a href="/item?id=1499">
                           <h6>Bitcoin will reach $350 by May 1st 2013</h6>
                        </a>
                        <li class="agree">10.53</li>
                        <li class="disagree">19.07</li>
                        <li class="active">3 days</li>
                     </div>
                     <div class="line-divider"></div>
                     <div class="filter">
                        <a href="/item?id=1444">
                           <h6>BFL will Not ship any ASICS to customers by May 1st</h6>
                        </a>
                        <li class="agree">15.61</li>
                        <li class="disagree">12.08</li>
                        <li class="active">2 weeks, 4 days</li>
                     </div>
                     <div class="line-divider"></div>
                     <div class="filter">
                        <a href="/item?id=1244">
                           <h6>Bitcoin will have fallen below $18/BTC by the end of April 2013</h6>
                        </a>
                        <li class="agree">1.10</li>
                        <li class="disagree">23.37</li>
                        <li class="active">2 weeks, 3 days</li>
                     </div>
                     <div class="line-divider"></div>
                     <div class="filter">
                        <a href="/item?id=969">
                           <h6>President Obama will use the word &quot;bitcoin&quot; in a public statement on or before July 4, 2013</h6>
                        </a>
                        <li class="agree">6.09</li>
                        <li class="disagree">17.35</li>
                        <li class="active">2 months, 3 weeks</li>
                     </div>
                     <div class="line-divider"></div>
                  </div>
                  <div>
                     <div class="filter">
                        <a href="/item?id=1507">
                           <h6>Bitcoin will reach $700 before May 1st, 2013.</h6>
                        </a>
                        <li class="agree">0.00</li>
                        <li class="disagree">0.30</li>
                        <li class="active">2 weeks, 4 days</li>
                     </div>
                     <div class="line-divider"></div>
                     <div class="filter">
                        <a href="/item?id=1506">
                           <h6>Bitcoin will trade above $450 on MtGox before May 1st 2013</h6>
                        </a>
                        <li class="agree">0.20</li>
                        <li class="disagree">0.81</li>
                        <li class="active">2 weeks, 4 days</li>
                     </div>
                     <div class="line-divider"></div>
                     <div class="filter">
                        <a href="/item?id=1505">
                           <h6>Butterfly Labs will accept payment for ASICs only in BTC prior to July 1st 2013</h6>
                        </a>
                        <li class="agree">0.00</li>
                        <li class="disagree">0.10</li>
                        <li class="active">2 months, 2 weeks</li>
                     </div>
                     <div class="line-divider"></div>
                     <div class="filter">
                        <a href="/item?id=1504">
                           <h6>Bitcoin will reach $450 by May 15th 2013</h6>
                        </a>
                        <li class="agree">0.20</li>
                        <li class="disagree">0.30</li>
                        <li class="active">1 month</li>
                     </div>
                     <div class="line-divider"></div>
                     <div class="filter">
                        <a href="/item?id=1502">
                           <h6>Litecoin Will Reach 8.00 By May 31st 2013 On BTC-e.com</h6>
                        </a>
                        <li class="agree">1.10</li>
                        <li class="disagree">0.20</li>
                        <li class="active">1 month, 2 weeks</li>
                     </div>
                     <div class="line-divider"></div>
                     <div class="filter">
                        <a href="/item?id=1500">
                           <h6>The new Xbox will require an always on internet connection in order to play games.</h6>
                        </a>
                        <li class="agree">0.00</li>
                        <li class="disagree">0.60</li>
                        <li class="active">1 month, 1 week</li>
                     </div>
                     <div class="line-divider"></div>
                     <div class="filter">
                        <a href="/item?id=1499">
                           <h6>Bitcoin will reach $350 by May 1st 2013</h6>
                        </a>
                        <li class="agree">10.53</li>
                        <li class="disagree">19.07</li>
                        <li class="active">3 days</li>
                     </div>
                     <div class="line-divider"></div>
                     <div class="filter">
                        <a href="/item?id=1498">
                           <h6>Verrazano will win the 2013 KY Derby</h6>
                        </a>
                        <li class="agree">0.00</li>
                        <li class="disagree">0.10</li>
                        <li class="active">3 weeks, 1 day</li>
                     </div>
                     <div class="line-divider"></div>
                     <div class="filter">
                        <a href="/item?id=1497">
                           <h6>The MtGox price of bitcoin will reach $400 USD before the end of 2013.</h6>
                        </a>
                        <li class="agree">0.20</li>
                        <li class="disagree">0.00</li>
                        <li class="active">8 months, 3 weeks</li>
                     </div>
                     <div class="line-divider"></div>
                     <div class="filter">
                        <a href="/item?id=1495">
                           <h6>The Miami Heat will win the NBA Championship in 2013</h6>
                        </a>
                        <li class="agree">0.10</li>
                        <li class="disagree">0.00</li>
                        <li class="active">1 month, 3 weeks</li>
                     </div>
                     <div class="line-divider"></div>
                  </div>
               </div>
               We have <a href="/list">more statements</a> to bet.
            </div>
         </div>
      </div>
   </div>
</div>
<?php echo $this->getChildHtml('footer') ?>
</body>
</html>